CREATE TABLE public.polity_accounts (
  user_id UUID PRIMARY KEY,
  authorization_subject TEXT NOT NULL UNIQUE,
  grant_receipt_id UUID NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);
