package com.odonta.polity.model;

public enum ConstitutionalHealthDiagnostic {
  ADMISSION_PATH_UNAVAILABLE,
  ORDINARY_GOVERNANCE_UNAVAILABLE,
  SANCTION_PATH_UNAVAILABLE,
  APPEAL_PATH_UNAVAILABLE,
  OFFICE_TERM_REVIEW_PATH_UNAVAILABLE,
  CONSTITUTIONAL_REVIEW_PATH_UNAVAILABLE,
  OFFICE_ELECTION_PATH_UNAVAILABLE,
  AMENDMENT_PATH_UNAVAILABLE,
  DISBANDMENT_PATH_UNAVAILABLE,
  CERTIFICATION_PATH_UNAVAILABLE,
  POLITY_DISBANDED
}
