package com.odonta.polity.model;

public enum GovernmentReadinessDiagnostic {
  NEEDS_MORE_STANDING_MEMBERS,
  ORDINARY_GOVERNANCE_AUTHORITY_UNAVAILABLE,
  ORDINARY_GOVERNANCE_ELECTORATE_UNAVAILABLE,
  OFFICE_ELECTION_AUTHORITY_UNAVAILABLE,
  OFFICE_ELECTION_ELECTORATE_UNAVAILABLE,
  CERTIFICATION_AUTHORITY_UNAVAILABLE,
  APPEAL_AUTHORITY_UNAVAILABLE,
  APPEAL_ELECTORATE_UNAVAILABLE,
  CONSTITUTIONAL_REVIEW_AUTHORITY_UNAVAILABLE,
  CONSTITUTIONAL_REVIEW_ELECTORATE_UNAVAILABLE,
  POLITY_DISBANDED
}
