package com.odonta.polity.model;

public enum PowerCode {
  ADMIT_MEMBER,
  INTRODUCE_MOTION,
  INTRODUCE_OFFICE_ASSIGNMENT,
  INTRODUCE_SANCTION,
  INTRODUCE_APPEAL,
  INTRODUCE_AMENDMENT,
  REQUEST_CERTIFICATION
}
