/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PolitiesIndexRouteImport } from './routes/polities/index'
import { Route as MeIndexRouteImport } from './routes/me/index'
import { Route as InboxIndexRouteImport } from './routes/inbox/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as ExploreIndexRouteImport } from './routes/explore/index'
import { Route as PolitiesNewRouteImport } from './routes/polities/new'
import { Route as ActionsNewRouteImport } from './routes/actions/new'
import { Route as PolitiesPolitySlugRouteRouteImport } from './routes/polities/$politySlug/route'
import { Route as PolitiesPolitySlugIndexRouteImport } from './routes/polities/$politySlug/index'
import { Route as PolitiesMembershipInvitationsInvitationIdRouteImport } from './routes/polities/membership-invitations/$invitationId'
import { Route as PolitiesInvitationsTokenRouteImport } from './routes/polities/invitations/$token'
import { Route as PolitiesPolitySlugRecordRouteImport } from './routes/polities/$politySlug/record'
import { Route as PolitiesPolitySlugGovernmentRouteImport } from './routes/polities/$politySlug/government'
import { Route as PolitiesPolitySlugMotionsIndexRouteImport } from './routes/polities/$politySlug/motions/index'
import { Route as PolitiesPolitySlugMotionsMotionIdRouteImport } from './routes/polities/$politySlug/motions/$motionId'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiesIndexRoute = PolitiesIndexRouteImport.update({
  id: '/polities/',
  path: '/polities/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeIndexRoute = MeIndexRouteImport.update({
  id: '/me/',
  path: '/me/',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxIndexRoute = InboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreIndexRoute = ExploreIndexRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiesNewRoute = PolitiesNewRouteImport.update({
  id: '/polities/new',
  path: '/polities/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsNewRoute = ActionsNewRouteImport.update({
  id: '/actions/new',
  path: '/actions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiesPolitySlugRouteRoute = PolitiesPolitySlugRouteRouteImport.update({
  id: '/polities/$politySlug',
  path: '/polities/$politySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiesPolitySlugIndexRoute = PolitiesPolitySlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PolitiesPolitySlugRouteRoute,
} as any)
const PolitiesMembershipInvitationsInvitationIdRoute =
  PolitiesMembershipInvitationsInvitationIdRouteImport.update({
    id: '/polities/membership-invitations/$invitationId',
    path: '/polities/membership-invitations/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PolitiesInvitationsTokenRoute =
  PolitiesInvitationsTokenRouteImport.update({
    id: '/polities/invitations/$token',
    path: '/polities/invitations/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const PolitiesPolitySlugRecordRoute =
  PolitiesPolitySlugRecordRouteImport.update({
    id: '/record',
    path: '/record',
    getParentRoute: () => PolitiesPolitySlugRouteRoute,
  } as any)
const PolitiesPolitySlugGovernmentRoute =
  PolitiesPolitySlugGovernmentRouteImport.update({
    id: '/government',
    path: '/government',
    getParentRoute: () => PolitiesPolitySlugRouteRoute,
  } as any)
const PolitiesPolitySlugMotionsIndexRoute =
  PolitiesPolitySlugMotionsIndexRouteImport.update({
    id: '/motions/',
    path: '/motions/',
    getParentRoute: () => PolitiesPolitySlugRouteRoute,
  } as any)
const PolitiesPolitySlugMotionsMotionIdRoute =
  PolitiesPolitySlugMotionsMotionIdRouteImport.update({
    id: '/motions/$motionId',
    path: '/motions/$motionId',
    getParentRoute: () => PolitiesPolitySlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/polities/$politySlug': typeof PolitiesPolitySlugRouteRouteWithChildren
  '/actions/new': typeof ActionsNewRoute
  '/polities/new': typeof PolitiesNewRoute
  '/explore/': typeof ExploreIndexRoute
  '/home/': typeof HomeIndexRoute
  '/inbox/': typeof InboxIndexRoute
  '/me/': typeof MeIndexRoute
  '/polities/': typeof PolitiesIndexRoute
  '/polities/$politySlug/government': typeof PolitiesPolitySlugGovernmentRoute
  '/polities/$politySlug/record': typeof PolitiesPolitySlugRecordRoute
  '/polities/invitations/$token': typeof PolitiesInvitationsTokenRoute
  '/polities/membership-invitations/$invitationId': typeof PolitiesMembershipInvitationsInvitationIdRoute
  '/polities/$politySlug/': typeof PolitiesPolitySlugIndexRoute
  '/polities/$politySlug/motions/$motionId': typeof PolitiesPolitySlugMotionsMotionIdRoute
  '/polities/$politySlug/motions/': typeof PolitiesPolitySlugMotionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/actions/new': typeof ActionsNewRoute
  '/polities/new': typeof PolitiesNewRoute
  '/explore': typeof ExploreIndexRoute
  '/home': typeof HomeIndexRoute
  '/inbox': typeof InboxIndexRoute
  '/me': typeof MeIndexRoute
  '/polities': typeof PolitiesIndexRoute
  '/polities/$politySlug/government': typeof PolitiesPolitySlugGovernmentRoute
  '/polities/$politySlug/record': typeof PolitiesPolitySlugRecordRoute
  '/polities/invitations/$token': typeof PolitiesInvitationsTokenRoute
  '/polities/membership-invitations/$invitationId': typeof PolitiesMembershipInvitationsInvitationIdRoute
  '/polities/$politySlug': typeof PolitiesPolitySlugIndexRoute
  '/polities/$politySlug/motions/$motionId': typeof PolitiesPolitySlugMotionsMotionIdRoute
  '/polities/$politySlug/motions': typeof PolitiesPolitySlugMotionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/polities/$politySlug': typeof PolitiesPolitySlugRouteRouteWithChildren
  '/actions/new': typeof ActionsNewRoute
  '/polities/new': typeof PolitiesNewRoute
  '/explore/': typeof ExploreIndexRoute
  '/home/': typeof HomeIndexRoute
  '/inbox/': typeof InboxIndexRoute
  '/me/': typeof MeIndexRoute
  '/polities/': typeof PolitiesIndexRoute
  '/polities/$politySlug/government': typeof PolitiesPolitySlugGovernmentRoute
  '/polities/$politySlug/record': typeof PolitiesPolitySlugRecordRoute
  '/polities/invitations/$token': typeof PolitiesInvitationsTokenRoute
  '/polities/membership-invitations/$invitationId': typeof PolitiesMembershipInvitationsInvitationIdRoute
  '/polities/$politySlug/': typeof PolitiesPolitySlugIndexRoute
  '/polities/$politySlug/motions/$motionId': typeof PolitiesPolitySlugMotionsMotionIdRoute
  '/polities/$politySlug/motions/': typeof PolitiesPolitySlugMotionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/polities/$politySlug'
    | '/actions/new'
    | '/polities/new'
    | '/explore/'
    | '/home/'
    | '/inbox/'
    | '/me/'
    | '/polities/'
    | '/polities/$politySlug/government'
    | '/polities/$politySlug/record'
    | '/polities/invitations/$token'
    | '/polities/membership-invitations/$invitationId'
    | '/polities/$politySlug/'
    | '/polities/$politySlug/motions/$motionId'
    | '/polities/$politySlug/motions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/actions/new'
    | '/polities/new'
    | '/explore'
    | '/home'
    | '/inbox'
    | '/me'
    | '/polities'
    | '/polities/$politySlug/government'
    | '/polities/$politySlug/record'
    | '/polities/invitations/$token'
    | '/polities/membership-invitations/$invitationId'
    | '/polities/$politySlug'
    | '/polities/$politySlug/motions/$motionId'
    | '/polities/$politySlug/motions'
  id:
    | '__root__'
    | '/'
    | '/sign-in'
    | '/polities/$politySlug'
    | '/actions/new'
    | '/polities/new'
    | '/explore/'
    | '/home/'
    | '/inbox/'
    | '/me/'
    | '/polities/'
    | '/polities/$politySlug/government'
    | '/polities/$politySlug/record'
    | '/polities/invitations/$token'
    | '/polities/membership-invitations/$invitationId'
    | '/polities/$politySlug/'
    | '/polities/$politySlug/motions/$motionId'
    | '/polities/$politySlug/motions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignInRoute: typeof SignInRoute
  PolitiesPolitySlugRouteRoute: typeof PolitiesPolitySlugRouteRouteWithChildren
  ActionsNewRoute: typeof ActionsNewRoute
  PolitiesNewRoute: typeof PolitiesNewRoute
  ExploreIndexRoute: typeof ExploreIndexRoute
  HomeIndexRoute: typeof HomeIndexRoute
  InboxIndexRoute: typeof InboxIndexRoute
  MeIndexRoute: typeof MeIndexRoute
  PolitiesIndexRoute: typeof PolitiesIndexRoute
  PolitiesInvitationsTokenRoute: typeof PolitiesInvitationsTokenRoute
  PolitiesMembershipInvitationsInvitationIdRoute: typeof PolitiesMembershipInvitationsInvitationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polities/': {
      id: '/polities/'
      path: '/polities'
      fullPath: '/polities/'
      preLoaderRoute: typeof PolitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/': {
      id: '/me/'
      path: '/me'
      fullPath: '/me/'
      preLoaderRoute: typeof MeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/': {
      id: '/inbox/'
      path: '/inbox'
      fullPath: '/inbox/'
      preLoaderRoute: typeof InboxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/': {
      id: '/explore/'
      path: '/explore'
      fullPath: '/explore/'
      preLoaderRoute: typeof ExploreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polities/new': {
      id: '/polities/new'
      path: '/polities/new'
      fullPath: '/polities/new'
      preLoaderRoute: typeof PolitiesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions/new': {
      id: '/actions/new'
      path: '/actions/new'
      fullPath: '/actions/new'
      preLoaderRoute: typeof ActionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polities/$politySlug': {
      id: '/polities/$politySlug'
      path: '/polities/$politySlug'
      fullPath: '/polities/$politySlug'
      preLoaderRoute: typeof PolitiesPolitySlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polities/$politySlug/': {
      id: '/polities/$politySlug/'
      path: '/'
      fullPath: '/polities/$politySlug/'
      preLoaderRoute: typeof PolitiesPolitySlugIndexRouteImport
      parentRoute: typeof PolitiesPolitySlugRouteRoute
    }
    '/polities/membership-invitations/$invitationId': {
      id: '/polities/membership-invitations/$invitationId'
      path: '/polities/membership-invitations/$invitationId'
      fullPath: '/polities/membership-invitations/$invitationId'
      preLoaderRoute: typeof PolitiesMembershipInvitationsInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polities/invitations/$token': {
      id: '/polities/invitations/$token'
      path: '/polities/invitations/$token'
      fullPath: '/polities/invitations/$token'
      preLoaderRoute: typeof PolitiesInvitationsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polities/$politySlug/record': {
      id: '/polities/$politySlug/record'
      path: '/record'
      fullPath: '/polities/$politySlug/record'
      preLoaderRoute: typeof PolitiesPolitySlugRecordRouteImport
      parentRoute: typeof PolitiesPolitySlugRouteRoute
    }
    '/polities/$politySlug/government': {
      id: '/polities/$politySlug/government'
      path: '/government'
      fullPath: '/polities/$politySlug/government'
      preLoaderRoute: typeof PolitiesPolitySlugGovernmentRouteImport
      parentRoute: typeof PolitiesPolitySlugRouteRoute
    }
    '/polities/$politySlug/motions/': {
      id: '/polities/$politySlug/motions/'
      path: '/motions'
      fullPath: '/polities/$politySlug/motions/'
      preLoaderRoute: typeof PolitiesPolitySlugMotionsIndexRouteImport
      parentRoute: typeof PolitiesPolitySlugRouteRoute
    }
    '/polities/$politySlug/motions/$motionId': {
      id: '/polities/$politySlug/motions/$motionId'
      path: '/motions/$motionId'
      fullPath: '/polities/$politySlug/motions/$motionId'
      preLoaderRoute: typeof PolitiesPolitySlugMotionsMotionIdRouteImport
      parentRoute: typeof PolitiesPolitySlugRouteRoute
    }
  }
}

interface PolitiesPolitySlugRouteRouteChildren {
  PolitiesPolitySlugGovernmentRoute: typeof PolitiesPolitySlugGovernmentRoute
  PolitiesPolitySlugRecordRoute: typeof PolitiesPolitySlugRecordRoute
  PolitiesPolitySlugIndexRoute: typeof PolitiesPolitySlugIndexRoute
  PolitiesPolitySlugMotionsMotionIdRoute: typeof PolitiesPolitySlugMotionsMotionIdRoute
  PolitiesPolitySlugMotionsIndexRoute: typeof PolitiesPolitySlugMotionsIndexRoute
}

const PolitiesPolitySlugRouteRouteChildren: PolitiesPolitySlugRouteRouteChildren =
  {
    PolitiesPolitySlugGovernmentRoute: PolitiesPolitySlugGovernmentRoute,
    PolitiesPolitySlugRecordRoute: PolitiesPolitySlugRecordRoute,
    PolitiesPolitySlugIndexRoute: PolitiesPolitySlugIndexRoute,
    PolitiesPolitySlugMotionsMotionIdRoute:
      PolitiesPolitySlugMotionsMotionIdRoute,
    PolitiesPolitySlugMotionsIndexRoute: PolitiesPolitySlugMotionsIndexRoute,
  }

const PolitiesPolitySlugRouteRouteWithChildren =
  PolitiesPolitySlugRouteRoute._addFileChildren(
    PolitiesPolitySlugRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignInRoute: SignInRoute,
  PolitiesPolitySlugRouteRoute: PolitiesPolitySlugRouteRouteWithChildren,
  ActionsNewRoute: ActionsNewRoute,
  PolitiesNewRoute: PolitiesNewRoute,
  ExploreIndexRoute: ExploreIndexRoute,
  HomeIndexRoute: HomeIndexRoute,
  InboxIndexRoute: InboxIndexRoute,
  MeIndexRoute: MeIndexRoute,
  PolitiesIndexRoute: PolitiesIndexRoute,
  PolitiesInvitationsTokenRoute: PolitiesInvitationsTokenRoute,
  PolitiesMembershipInvitationsInvitationIdRoute:
    PolitiesMembershipInvitationsInvitationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
