/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PolitiesIndexRouteImport } from './routes/polities/index'
import { Route as MeIndexRouteImport } from './routes/me/index'
import { Route as InboxIndexRouteImport } from './routes/inbox/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as ExploreIndexRouteImport } from './routes/explore/index'
import { Route as PolitiesNewRouteImport } from './routes/polities/new'
import { Route as ActionsNewRouteImport } from './routes/actions/new'
import { Route as PolitiesPolityIdRouteRouteImport } from './routes/polities/$polityId/route'
import { Route as PolitiesPolityIdIndexRouteImport } from './routes/polities/$polityId/index'
import { Route as PolitiesMembershipInvitationsInvitationIdRouteImport } from './routes/polities/membership-invitations/$invitationId'
import { Route as PolitiesInvitationsTokenRouteImport } from './routes/polities/invitations/$token'
import { Route as PolitiesPolityIdRecordRouteImport } from './routes/polities/$polityId/record'
import { Route as PolitiesPolityIdGovernmentRouteImport } from './routes/polities/$polityId/government'
import { Route as PolitiesPolityIdMotionsIndexRouteImport } from './routes/polities/$polityId/motions/index'
import { Route as PolitiesPolityIdMotionsMotionIdRouteImport } from './routes/polities/$polityId/motions/$motionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiesIndexRoute = PolitiesIndexRouteImport.update({
  id: '/polities/',
  path: '/polities/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeIndexRoute = MeIndexRouteImport.update({
  id: '/me/',
  path: '/me/',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxIndexRoute = InboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreIndexRoute = ExploreIndexRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiesNewRoute = PolitiesNewRouteImport.update({
  id: '/polities/new',
  path: '/polities/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsNewRoute = ActionsNewRouteImport.update({
  id: '/actions/new',
  path: '/actions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiesPolityIdRouteRoute = PolitiesPolityIdRouteRouteImport.update({
  id: '/polities/$polityId',
  path: '/polities/$polityId',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiesPolityIdIndexRoute = PolitiesPolityIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PolitiesPolityIdRouteRoute,
} as any)
const PolitiesMembershipInvitationsInvitationIdRoute =
  PolitiesMembershipInvitationsInvitationIdRouteImport.update({
    id: '/polities/membership-invitations/$invitationId',
    path: '/polities/membership-invitations/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PolitiesInvitationsTokenRoute =
  PolitiesInvitationsTokenRouteImport.update({
    id: '/polities/invitations/$token',
    path: '/polities/invitations/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const PolitiesPolityIdRecordRoute = PolitiesPolityIdRecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => PolitiesPolityIdRouteRoute,
} as any)
const PolitiesPolityIdGovernmentRoute =
  PolitiesPolityIdGovernmentRouteImport.update({
    id: '/government',
    path: '/government',
    getParentRoute: () => PolitiesPolityIdRouteRoute,
  } as any)
const PolitiesPolityIdMotionsIndexRoute =
  PolitiesPolityIdMotionsIndexRouteImport.update({
    id: '/motions/',
    path: '/motions/',
    getParentRoute: () => PolitiesPolityIdRouteRoute,
  } as any)
const PolitiesPolityIdMotionsMotionIdRoute =
  PolitiesPolityIdMotionsMotionIdRouteImport.update({
    id: '/motions/$motionId',
    path: '/motions/$motionId',
    getParentRoute: () => PolitiesPolityIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/polities/$polityId': typeof PolitiesPolityIdRouteRouteWithChildren
  '/actions/new': typeof ActionsNewRoute
  '/polities/new': typeof PolitiesNewRoute
  '/explore/': typeof ExploreIndexRoute
  '/home/': typeof HomeIndexRoute
  '/inbox/': typeof InboxIndexRoute
  '/me/': typeof MeIndexRoute
  '/polities/': typeof PolitiesIndexRoute
  '/polities/$polityId/government': typeof PolitiesPolityIdGovernmentRoute
  '/polities/$polityId/record': typeof PolitiesPolityIdRecordRoute
  '/polities/invitations/$token': typeof PolitiesInvitationsTokenRoute
  '/polities/membership-invitations/$invitationId': typeof PolitiesMembershipInvitationsInvitationIdRoute
  '/polities/$polityId/': typeof PolitiesPolityIdIndexRoute
  '/polities/$polityId/motions/$motionId': typeof PolitiesPolityIdMotionsMotionIdRoute
  '/polities/$polityId/motions/': typeof PolitiesPolityIdMotionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actions/new': typeof ActionsNewRoute
  '/polities/new': typeof PolitiesNewRoute
  '/explore': typeof ExploreIndexRoute
  '/home': typeof HomeIndexRoute
  '/inbox': typeof InboxIndexRoute
  '/me': typeof MeIndexRoute
  '/polities': typeof PolitiesIndexRoute
  '/polities/$polityId/government': typeof PolitiesPolityIdGovernmentRoute
  '/polities/$polityId/record': typeof PolitiesPolityIdRecordRoute
  '/polities/invitations/$token': typeof PolitiesInvitationsTokenRoute
  '/polities/membership-invitations/$invitationId': typeof PolitiesMembershipInvitationsInvitationIdRoute
  '/polities/$polityId': typeof PolitiesPolityIdIndexRoute
  '/polities/$polityId/motions/$motionId': typeof PolitiesPolityIdMotionsMotionIdRoute
  '/polities/$polityId/motions': typeof PolitiesPolityIdMotionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/polities/$polityId': typeof PolitiesPolityIdRouteRouteWithChildren
  '/actions/new': typeof ActionsNewRoute
  '/polities/new': typeof PolitiesNewRoute
  '/explore/': typeof ExploreIndexRoute
  '/home/': typeof HomeIndexRoute
  '/inbox/': typeof InboxIndexRoute
  '/me/': typeof MeIndexRoute
  '/polities/': typeof PolitiesIndexRoute
  '/polities/$polityId/government': typeof PolitiesPolityIdGovernmentRoute
  '/polities/$polityId/record': typeof PolitiesPolityIdRecordRoute
  '/polities/invitations/$token': typeof PolitiesInvitationsTokenRoute
  '/polities/membership-invitations/$invitationId': typeof PolitiesMembershipInvitationsInvitationIdRoute
  '/polities/$polityId/': typeof PolitiesPolityIdIndexRoute
  '/polities/$polityId/motions/$motionId': typeof PolitiesPolityIdMotionsMotionIdRoute
  '/polities/$polityId/motions/': typeof PolitiesPolityIdMotionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/polities/$polityId'
    | '/actions/new'
    | '/polities/new'
    | '/explore/'
    | '/home/'
    | '/inbox/'
    | '/me/'
    | '/polities/'
    | '/polities/$polityId/government'
    | '/polities/$polityId/record'
    | '/polities/invitations/$token'
    | '/polities/membership-invitations/$invitationId'
    | '/polities/$polityId/'
    | '/polities/$polityId/motions/$motionId'
    | '/polities/$polityId/motions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actions/new'
    | '/polities/new'
    | '/explore'
    | '/home'
    | '/inbox'
    | '/me'
    | '/polities'
    | '/polities/$polityId/government'
    | '/polities/$polityId/record'
    | '/polities/invitations/$token'
    | '/polities/membership-invitations/$invitationId'
    | '/polities/$polityId'
    | '/polities/$polityId/motions/$motionId'
    | '/polities/$polityId/motions'
  id:
    | '__root__'
    | '/'
    | '/polities/$polityId'
    | '/actions/new'
    | '/polities/new'
    | '/explore/'
    | '/home/'
    | '/inbox/'
    | '/me/'
    | '/polities/'
    | '/polities/$polityId/government'
    | '/polities/$polityId/record'
    | '/polities/invitations/$token'
    | '/polities/membership-invitations/$invitationId'
    | '/polities/$polityId/'
    | '/polities/$polityId/motions/$motionId'
    | '/polities/$polityId/motions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PolitiesPolityIdRouteRoute: typeof PolitiesPolityIdRouteRouteWithChildren
  ActionsNewRoute: typeof ActionsNewRoute
  PolitiesNewRoute: typeof PolitiesNewRoute
  ExploreIndexRoute: typeof ExploreIndexRoute
  HomeIndexRoute: typeof HomeIndexRoute
  InboxIndexRoute: typeof InboxIndexRoute
  MeIndexRoute: typeof MeIndexRoute
  PolitiesIndexRoute: typeof PolitiesIndexRoute
  PolitiesInvitationsTokenRoute: typeof PolitiesInvitationsTokenRoute
  PolitiesMembershipInvitationsInvitationIdRoute: typeof PolitiesMembershipInvitationsInvitationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polities/': {
      id: '/polities/'
      path: '/polities'
      fullPath: '/polities/'
      preLoaderRoute: typeof PolitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/': {
      id: '/me/'
      path: '/me'
      fullPath: '/me/'
      preLoaderRoute: typeof MeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/': {
      id: '/inbox/'
      path: '/inbox'
      fullPath: '/inbox/'
      preLoaderRoute: typeof InboxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/': {
      id: '/explore/'
      path: '/explore'
      fullPath: '/explore/'
      preLoaderRoute: typeof ExploreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polities/new': {
      id: '/polities/new'
      path: '/polities/new'
      fullPath: '/polities/new'
      preLoaderRoute: typeof PolitiesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions/new': {
      id: '/actions/new'
      path: '/actions/new'
      fullPath: '/actions/new'
      preLoaderRoute: typeof ActionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polities/$polityId': {
      id: '/polities/$polityId'
      path: '/polities/$polityId'
      fullPath: '/polities/$polityId'
      preLoaderRoute: typeof PolitiesPolityIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polities/$polityId/': {
      id: '/polities/$polityId/'
      path: '/'
      fullPath: '/polities/$polityId/'
      preLoaderRoute: typeof PolitiesPolityIdIndexRouteImport
      parentRoute: typeof PolitiesPolityIdRouteRoute
    }
    '/polities/membership-invitations/$invitationId': {
      id: '/polities/membership-invitations/$invitationId'
      path: '/polities/membership-invitations/$invitationId'
      fullPath: '/polities/membership-invitations/$invitationId'
      preLoaderRoute: typeof PolitiesMembershipInvitationsInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polities/invitations/$token': {
      id: '/polities/invitations/$token'
      path: '/polities/invitations/$token'
      fullPath: '/polities/invitations/$token'
      preLoaderRoute: typeof PolitiesInvitationsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polities/$polityId/record': {
      id: '/polities/$polityId/record'
      path: '/record'
      fullPath: '/polities/$polityId/record'
      preLoaderRoute: typeof PolitiesPolityIdRecordRouteImport
      parentRoute: typeof PolitiesPolityIdRouteRoute
    }
    '/polities/$polityId/government': {
      id: '/polities/$polityId/government'
      path: '/government'
      fullPath: '/polities/$polityId/government'
      preLoaderRoute: typeof PolitiesPolityIdGovernmentRouteImport
      parentRoute: typeof PolitiesPolityIdRouteRoute
    }
    '/polities/$polityId/motions/': {
      id: '/polities/$polityId/motions/'
      path: '/motions'
      fullPath: '/polities/$polityId/motions/'
      preLoaderRoute: typeof PolitiesPolityIdMotionsIndexRouteImport
      parentRoute: typeof PolitiesPolityIdRouteRoute
    }
    '/polities/$polityId/motions/$motionId': {
      id: '/polities/$polityId/motions/$motionId'
      path: '/motions/$motionId'
      fullPath: '/polities/$polityId/motions/$motionId'
      preLoaderRoute: typeof PolitiesPolityIdMotionsMotionIdRouteImport
      parentRoute: typeof PolitiesPolityIdRouteRoute
    }
  }
}

interface PolitiesPolityIdRouteRouteChildren {
  PolitiesPolityIdGovernmentRoute: typeof PolitiesPolityIdGovernmentRoute
  PolitiesPolityIdRecordRoute: typeof PolitiesPolityIdRecordRoute
  PolitiesPolityIdIndexRoute: typeof PolitiesPolityIdIndexRoute
  PolitiesPolityIdMotionsMotionIdRoute: typeof PolitiesPolityIdMotionsMotionIdRoute
  PolitiesPolityIdMotionsIndexRoute: typeof PolitiesPolityIdMotionsIndexRoute
}

const PolitiesPolityIdRouteRouteChildren: PolitiesPolityIdRouteRouteChildren = {
  PolitiesPolityIdGovernmentRoute: PolitiesPolityIdGovernmentRoute,
  PolitiesPolityIdRecordRoute: PolitiesPolityIdRecordRoute,
  PolitiesPolityIdIndexRoute: PolitiesPolityIdIndexRoute,
  PolitiesPolityIdMotionsMotionIdRoute: PolitiesPolityIdMotionsMotionIdRoute,
  PolitiesPolityIdMotionsIndexRoute: PolitiesPolityIdMotionsIndexRoute,
}

const PolitiesPolityIdRouteRouteWithChildren =
  PolitiesPolityIdRouteRoute._addFileChildren(
    PolitiesPolityIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PolitiesPolityIdRouteRoute: PolitiesPolityIdRouteRouteWithChildren,
  ActionsNewRoute: ActionsNewRoute,
  PolitiesNewRoute: PolitiesNewRoute,
  ExploreIndexRoute: ExploreIndexRoute,
  HomeIndexRoute: HomeIndexRoute,
  InboxIndexRoute: InboxIndexRoute,
  MeIndexRoute: MeIndexRoute,
  PolitiesIndexRoute: PolitiesIndexRoute,
  PolitiesInvitationsTokenRoute: PolitiesInvitationsTokenRoute,
  PolitiesMembershipInvitationsInvitationIdRoute:
    PolitiesMembershipInvitationsInvitationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
